### ISSUE TITLE
'undefined' is not a function after updating to 2.3

### ISSUE THREAD

**Issue by mmanela** [mmanela/chutzpah#90]
<b>greggbjensen[CodePlex]</b> <br />The new version of Chutzpah seems to be having trouble resolving references. I have paths to both jQuery and underscore, and it cannot find them even though they are correct. Running them in the browser with the Visual Studio Chutzpah add-in works fine.
 All tests worked fine in version 2.2.
JS Error: ReferenceError: Can't find variable: _
 in file:///c:/projects/.../scripts/libs/plugins.js (line 495)
in file:///c:/projects/.../scripts/libs/plugins.js (line 658)
While Running:c:\projects...\scripts\test\libs\plugins\tests.js
Test 'DateUtil:should format date and time' failed
    Died on test #1     at file:///C:/Users/.../AppData/Local/Microsoft/VisualStudio/11.0/Extensions/xk1wwyp0.j5k/TestFiles/QUnit/qunit.js:343
    at file:///C:/Projects/.../Scripts/test/libs/plugins/tests.js:39
    at file:///C:/Projects/.../Scripts/test/libs/plugins/tests.js:41: 'undefined' is not a function (evaluating '$.substitute')
in C:\Projects...\Scripts\test\libs\plugins\tests.js (line 34)
Here is what the test file looks like:
/// ltreference path=quot../../../libs/jquery/jquery.jsquot /gt
/// ltreference path=quot../../../libs/underscore/underscore.jsquot /gt
/// ltreference path=quot../../qunit.jsquot /gt
/// ltreference path=quot../../../libs/plugins.jsquot /gt

/_jshint browser:true, jquery:true */
/_global _, test, module, equal */

(function ($) {

```
module('$.substitute');

test('should replace named tokens in string', function () {
 ...
});

module('DateUtil');

test('should format date and time', function () {
 ...
});
```

})(jQuery);
Here is the file structure
Scripts\
    libs\
        underscore\
            underscore.js
        jquery\
            jquery.js
        plugins.js
    test\
        libs\
            plugins\
                tests.js
                ui.html
Here is what the plugins file looks like
/// ltreference path=quotjquery/jquery.jsquot /gt
/// ltreference path=quotunderscore/underscore.jsquot /gt
/// ltreference path=quotknockout/knockout.jsquot /gt
/// ltreference path=quotdatepicker/bootstrap-datepicker.jsquot /gt
...

/_jshint browser: true, jquery: true_/
/*global _, ko, setTimeout, Log */

DateUtil = {

```
formatDate: function (date, formatString) {
 ...
}
```

};

(function ($) {
    ...

```
$.substitute = function(str, sub) {
  ...
};
```

})(jQuery);
